
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-7pm-2
owner: ucsb-cs156-w24
repo_name: team03-w24-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-ReqRequest-Placeholders","number":155,"title":"Andy req request placeholders","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/155"},{"author":{"id":"MDQ6VXNlcjE1ODMzOTY4","is_bot":false,"login":"ashton-wong","name":"Ashton Wong"},"headRefName":"aw-UCSBDiningCommonsMenuItem-form","number":154,"title":"AW - Menu Item Form Components + Tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/154"},{"author":{"id":"MDQ6VXNlcjMyMzQ1NzI0","is_bot":false,"login":"Kavya75","name":"Kavya Verma"},"headRefName":"KV-HelpRequest-placeholders","number":153,"title":"KV - Copy Placeholders for HelpRequest pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/153"},{"author":{"id":"MDQ6VXNlcjMyMzQ1NzI0","is_bot":false,"login":"Kavya75","name":"Kavya Verma"},"headRefName":"kv-HelpRequest-table-component","number":152,"title":"KV - Table Component for HelpRequest plus tests (new pull request)","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/152"},{"author":{"id":"U_kgDOBdC7MQ","is_bot":false,"login":"michaelw1985","name":"Michael W"},"headRefName":"michael-Articles-fixtures","number":150,"title":"mw - added fixtures for Articles","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/150"},{"author":{"id":"U_kgDOBdC7MQ","is_bot":false,"login":"michaelw1985","name":"Michael W"},"headRefName":"michael-Articles-backend","number":149,"title":"mw - copied files for backend CRUF API Articles from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/149"},{"author":{"id":"MDQ6VXNlcjMyMzQ1NzI0","is_bot":false,"login":"Kavya75","name":"Kavya Verma"},"headRefName":"kv-HelpRequest-form-component","number":146,"title":"KV -  Form Component for HelpRequest plus tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/146"},{"author":{"id":"MDQ6VXNlcjE1ODMzOTY4","is_bot":false,"login":"ashton-wong","name":"Ashton Wong"},"headRefName":"aw-UCSBDiningCommonsMenuItem-fixtures","number":145,"title":"AW - Fixtures for Menu Items","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/145"}]
