
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-7pm-2
owner: ucsb-cs156-w24
repo_name: team03-w24-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjMyMzQ1NzI0","is_bot":false,"login":"Kavya75","name":"Kavya Verma"},"headRefName":"KV-HelpRequest-backend","number":77,"title":"KV - Copy files for Backend CRUD API HelpRequest from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/77"},{"author":{"id":"U_kgDOBXc-yA","is_bot":false,"login":"nguyenliliana","name":""},"headRefName":"LN-MenuItemReview-index-page","number":76,"title":"ln - MenuItemReview Index Page","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/76"},{"author":{"id":"U_kgDOBXc-yA","is_bot":false,"login":"nguyenliliana","name":""},"headRefName":"LN-MenuItemReview-edit-page","number":75,"title":"ln - MenuItemReview EditPage","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/75"}]
