
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-7pm-2
owner: ucsb-cs156-w24
repo_name: team03-w24-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjUzMTg4OTY4","is_bot":false,"login":"elaineeeho","name":"Elaine Ho"},"headRefName":"eh-UCSBOrganization-table-component","number":64,"title":"eh - UCSBOrganization table component","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/64"},{"author":{"id":"MDQ6VXNlcjUzMTg4OTY4","is_bot":false,"login":"elaineeeho","name":"Elaine Ho"},"headRefName":"eh-UCSBOrganization-form-component","number":63,"title":"eh - UCSBOrganization Form Component","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/63"},{"author":{"id":"MDQ6VXNlcjUzMTg4OTY4","is_bot":false,"login":"elaineeeho","name":"Elaine Ho"},"headRefName":"eh-UCSBOrganization-fixtures","number":62,"title":"eh - Created UCSBOrganization fixtures","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/62"},{"author":{"id":"MDQ6VXNlcjUzMTg4OTY4","is_bot":false,"login":"elaineeeho","name":"Elaine Ho"},"headRefName":"eh-UCSBOrganization-backend","number":61,"title":"eh - Copy files for backend CRUD API UCSBOrganization","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/61"}]
