
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-7pm-2
owner: ucsb-cs156-w24
repo_name: team03-w24-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-ReqRequest-EditPage","number":175,"title":"Andy req request edit page","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/175"},{"author":{"id":"MDQ6VXNlcjUzMTg4OTY4","is_bot":false,"login":"elaineeeho","name":"Elaine Ho"},"headRefName":"eh-UCSBOrganization-edit-page","number":173,"title":"eh - fixed errors with boolean values not displaying","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/173"},{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-ReqRequest-IndexPage","number":163,"title":"Andy req request index page","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/163"},{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-ReqRequest-CreatePage","number":156,"title":"Andy req request create page","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/156"},{"author":{"id":"MDQ6VXNlcjc3NDczMTE0","is_bot":false,"login":"andy-gale","name":"Andy Gale"},"headRefName":"Andy-ReqRequest-Placeholders","number":155,"title":"Andy req request placeholders","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-2/pull/155"}]
